name: adhara_socket_io
description: Websocket by socket.io for flutter by adhara, supports both iOS and Android
version: 0.4.2
author: Rohit R. Abbadi <rohit@infitio.com>
homepage: https://github.com/infitio/flutter_socket_io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  streams_channel: ^0.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.infitio.adharasocketio
        pluginClass: AdharaSocketIoPlugin
#      ios:
#        pluginClass: AdharasocketioPlugin
#      macos:
#        pluginClass: AdharasocketioPlugin
